[package]
name = "mime_magic"
version = "0.1.0"
authors = ["Ronen Ulanovsky <ronen.ulanovsky.5@gmail.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
quick-xml = "^0.17.2"

[dependencies]